[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://localhost:4723"
status-endpoint = "/status"

[[relay.configs]]
max-sessions = 1
stereotype = '{"udid":"emulator-5554", "platformName":"android", "appium:platformVersion":"11"}'

[[relay.configs]]
max-sessions = 1
stereotype = '{"udid":"07AE47DA-E6C9-4D03-B647-4DFE1EE733D7", "platformName":"iOS","appium:platformVersion":"15.4"}'
